<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Official Receipt</title>
    <style>
        body { font-family: 'Helvetica', 'Arial', sans-serif; font-size: 14px; line-height: 1.4; color: #333; }
        .header-table { width: 100%; border-bottom: 2px solid #2C3E50; padding-bottom: 20px; margin-bottom: 30px; }
        .company-name { font-size: 20px; font-weight: bold; color: #2C3E50; text-transform: uppercase; }
        .doc-title { font-size: 24px; font-weight: bold; color: #B08D55; text-align: right; text-transform: uppercase; }
        
        .info-table { width: 100%; margin-bottom: 30px; }
        .info-label { font-weight: bold; color: #555; width: 120px; }
        
        .receipt-box { border: 1px solid #ddd; padding: 20px; background-color: #f9f9f9; margin-bottom: 30px; }
        .amount-row { font-size: 18px; font-weight: bold; color: #2C3E50; padding-top: 10px; border-top: 1px solid #eee; margin-top: 10px; }
        
        .footer { position: fixed; bottom: 30px; left: 0; right: 0; text-align: center; font-size: 10px; color: #777; border-top: 1px solid #eee; padding-top: 10px; }
        
        table.data-grid { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        table.data-grid th { background-color: #2C3E50; color: white; padding: 8px; text-align: left; }
        table.data-grid td { border-bottom: 1px solid #ddd; padding: 8px; }
        .text-right { text-align: right; }
    </style>
</head>
<body>
    <table class="header-table">
        <tr>
            <td valign="top">
                <img src="{{ public_path('images/logo/cchpl-official-logo.png') }}" alt="CCHPL Logo" style="max-height: 50px; margin-bottom: 5px;">
                <div style="margin-top: 5px; font-size: 12px;">Maseru, Lesotho<br>finance@cchpl.org.ls</div>
            </td>
            <td valign="top" class="text-right">
                <div class="doc-title">Official Receipt</div>
                <div style="margin-top: 10px;">
                    Receipt #: <strong>{{ $payment->receipt_number ?? 'PENDING' }}</strong><br>
                    Date: {{ $payment->verified_at ? $payment->verified_at->format('d M Y') : now()->format('d M Y') }}
                </div>
            </td>
        </tr>
    </table>

    <div class="receipt-box">
        <table class="info-table">
            <tr>
                <td class="info-label">Received From:</td>
                <td><strong>{{ $user->name }}</strong></td>
            </tr>
            <tr>
                <td class="info-label">Member ID:</td>
                <td>{{ $membership->member_id ?? 'N/A' }}</td>
            </tr>
            <tr>
                <td class="info-label">Email:</td>
                <td>{{ $user->email }}</td>
            </tr>
        </table>
    </div>

    <table class="data-grid">
        <thead>
            <tr>
                <th>Description</th>
                <th>Reference</th>
                <th class="text-right">Amount (LSL)</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    Membership Fee - {{ $membership->category?->name ?? 'Unknown category' }}<br>
                    <small>Payment via {{ ucfirst($payment->provider) }}</small>
                </td>
                <td>{{ $payment->transaction_reference }}</td>
                <td class="text-right">{{ number_format($payment->amount, 2) }}</td>
            </tr>
            <tr>
                <td colspan="2" class="text-right" style="border: none; padding-top: 20px;"><strong>Total Received:</strong></td>
                <td class="text-right" style="border: none; padding-top: 20px; font-size: 16px; font-weight: bold;">
                    M {{ number_format($payment->amount, 2) }}
                </td>
            </tr>
        </tbody>
    </table>

    <p style="margin-top: 40px; text-align: center; font-style: italic; color: #777;">
        Thank you for your payment. This document serves as an official proof of payment.
    </p>

    <div class="footer">
        CCHPL-FIN-003 &bull; Generated by CCHPL System
    </div>
</body>
</html>